apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oficina.fullname" . }}-agent
  labels:
    {{- include "oficina.agentLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.agent.replicas }}
  selector:
    matchLabels:
      {{- include "oficina.agentSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "oficina.agentSelectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - --server
            - http://{{ include "oficina.fullname" . }}-server:{{ .Values.server.service.port }}
            - --name
            - {{ .Values.agent.name }}
            {{- if .Values.agent.labels }}
            - --labels
            - {{ .Values.agent.labels }}
            {{- end }}
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
